sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tR5fy9ahmZqBFmRDJR1
    access-key-secret: kZvCD23xeKwRGbsOFSR1KIaTFXiZXg
    bucket-name: sky-itcast5556
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wx1d1a758e5df9f0c0
    secret: ad9ba93557d01eb4ef28b99f5029d9fe
